language: bash
arch:
  - amd64
services:
  - docker
jobs:
  include:
    - stage: build branch
      script:
        - set -e
        - docker build -t chrisjohnson00/handbrake_filemove_reprocessor -f Dockerfile .
        - docker run chrisjohnson00/handbrake_filemove_reprocessor python -m flake8
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/handbrake_filemove_reprocessor chrisjohnson00/handbrake_filemove_reprocessor:$TRAVIS_BRANCH
        - docker push chrisjohnson00/handbrake_filemove_reprocessor:$TRAVIS_BRANCH
      if: tag is blank
    - stage: build tag
      script:
        - docker build -t chrisjohnson00/handbrake_filemove_reprocessor -f Dockerfile .
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/handbrake_filemove_reprocessor chrisjohnson00/handbrake_filemove_reprocessor:$TRAVIS_TAG
        - docker push chrisjohnson00/handbrake_filemove_reprocessor:$TRAVIS_TAG
        - docker push chrisjohnson00/handbrake_filemove_reprocessor
      if: tag IS present
