apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'handbrake-job-file-mover-reprocessor'
  namespace: 'handbrake-jobs'
  labels:
    app: 'handbrake-job-file-mover-reprocessor'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'handbrake-job-file-mover-reprocessor'
  template:
    metadata:
      labels:
        app: 'handbrake-job-file-mover-reprocessor'
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: 'handbrake-job-file-mover-reprocessor'
        image: chrisjohnson00/reprocess-files:v2.0.0-rc-1599611293.0
        volumeMounts:
        - name: 'output'
          mountPath: '/output'
        env:
        - name: 'PULSAR_TOPIC'
          value: 'handbrake-file-move'
        - name: 'PULSAR_SERVER'
          value: 'pulsar-broker.pulsar:6650'
      volumes:
      - name: 'output'
        nfs:
          server: '192.168.1.131'
          path: '/data/k8s/output'
